### ISSUE TITLE
Error scraping user page

### ISSUE THREAD

**Issue by networker017** [rzlyp/instagram-scraping#23]
Hello,

Why I get this error? The user exists and is not private. But others username are work successfully but not all. Why?

**Comment by ppedrazzi** [comment]
I am getting this same issue: "Unhandled rejection Error: Error scraping user page" for any username.

**Comment by ExpErgio** [comment]
I have the same error :(

**Comment by rzlyp** [comment]
still figure out, instagram has changed their stucture

**Comment by ExpErgio** [comment]
And is it possible to do something to fix it? :(

**Comment by ExpErgio** [comment]
The point is that when I downloaded it and used it for the first time, it did work fine. I did 6 or 7 tests to see that it worked well, and it perfectly extracted all the information.

But after those 6 or 7 times, it was when it stopped working, and that error appeared

**Comment by rzlyp** [comment]
@ExpErgio just add http header and migrate from request to Axios, already tested more than 20 requests with a different username, all clear with no errors.

**Comment by ExpErgio** [comment]
I get the same error again.

Even so, I think it is because Instagram and its anti-bot system do not allow these types of actions unless they are punctual and occasional.

Look at this code: 

```js
const accounts = [
     "sergio98ssct",
     "marvel",
     "excelsior_ds",
     "dccomics",
     "disneyplus",
     "discord",
     "universal",
     "paramount",
     "bbc_news",
     "marvelspain"
]

async function show_last_post(){
     for(var i=0 ; i<accounts.length ; i++){
          let result = await ig.scrapeUserPage(accounts[i])
          console.log("Link: https://www.instagram.com/p/"+result.medias[0].node.shortcode)
          console.log("Image: "+result.medias[0].node.display_url)
     }
}

show_last_post();
```

I have checked. If you want to make several requests almost at the same time, when you are going to extract the information from the 4th or 5th account, the error appears again, and nothing works anymore; and it doesn't work for at least 24 hours.

If you are going to use npm moderately, there will be no problem. The problem is for those of us who need to give it a more massive use than normal. And I think that Facebook's anti-bot system is going to prevent some (like me) from being able to use it.

Unless you come up with some more idea that we can try (the option of creating a "Sleep" function that makes a certain amount of seconds wait between one search and another, is an option, but not recommended in the long term, given that when there are many accounts, the waiting time will be excessive)

@rzlyp

**Comment by rzlyp** [comment]
@ExpErgio what if you put a delay on each loop? so make it synchronous to avoid the anti-bot system

example :
```
const delay = (amount = number) => {
    return new Promise((resolve) => {
      setTimeout(resolve, amount);
    });
 }
 
for(var i=0 ; i<accounts.length ; i++){
          let result = await ig.scrapeUserPage(accounts[i])
          await delay(1000) //delay for a second before the next request
}
```

**Comment by ExpErgio** [comment]
For the same reason that I told you before: because in the end, the delay between one extraction and another would be excessive with, for example, 500 accounts.

I have a Discord bot, and each server saves the Instagram accounts it wants to receive notifications from in a table (SQLite).

The bot checks the entire database every 5 minutes. It parses 1 by 1, all the accounts of all the tables of all the servers of the database.

[Image of SQLite - 1](https://cdn.discordapp.com/attachments/823263020246761523/861566801296490516/tak1.png)

```js
setInterval(async function() {
     db_instagram.all(`SELECT * FROM sqlite_master`, (err, filas) => {
          if(filas) for(var i=0 ; i<filas.length ; i++) ins_check(filas[i].name)
     })
}, 300000);
```

And then, inside each table, I check all the accounts, to know if the code of the last post I have saved matches the last one I extract thanks to the NPM or not.

If it is the same, I do nothing, but if they are different, I send the new post as a message, and update the database.

[Image of SQLite - 2](https://cdn.discordapp.com/attachments/823263020246761523/861568150620209173/tak2.png)

```js
async function ins_check(name){
     db_instagram.all(`SELECT * FROM '${name}'`, async (err, filas) => {
          if(err || !filas) return;
          for(var i=0 ; i<filas.length ; i++){
               let result = await ig.scrapeUserPage(filas[i].cuenta)
               // etc
          }
     })
}
```
@rzlyp

**Comment by rzlyp** [comment]
@ExpErgio i think there is no way to handle that many requests because Instagram has a set rate limiter per minutes

the only way to bypass it is using a dynamic proxy like https://brightdata.com, but I can't afford it because no source for free proxy

**Comment by restyler** [comment]
brightdata proxies are hammered with hundreds of other users tryin to access Instagram, so you will get redirects to login page all the time. I recommend using instalyze.me instagram API instead (and specifically /proxy endpoint which allows to provide any instagram url for scraping) .

**Comment by rzlyp** [comment]
thank you for your feedback, i'll try to make this in the next version.

feel free if you want to collaborate develop this module.

Thank you.

**Comment by pietroconta** [comment]
i am getting the exact same error
